---
title: 'Google Maps'
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
  pdf_document:
  toc: yes
---

NOTE: remember ot insert a valid Google Maps Directions API key below!

## Read in intersection coordinates
```{r}
# NOTE: The following path command only works in RStudio, not R (incl. console)
path <- paste(dirname(rstudioapi::getActiveDocumentContext()$path),"../data/Distance matrix for manual graph/Coordinates.csv", sep="/")
intersectionCoords <- read.csv(path, col.names = c("latitude", "longitude"), header=FALSE)
intersectionCoords
```

## Route solution
```{r}
# Route solution
# routeNodes <- c(0,1,2,3,4,3,5,3,6) # test

# routeNodes <- c(0, 1, 6, 8, 7, 11, 14, 13, 20, 21, 20, 17, 12, 10, 12, 13, 14, 18, 15, 19, 22, 23, 21, 18, 15, 11, 7, 5, 6, 8, 9, 16, 19, 22, 16, 9, 3, 4, 3, 2, 1, 0) # Carlgorithm

routeNodes <- c(0, 1, 6, 5, 7, 11, 14, 13, 12, 10, 12, 17, 20, 21, 20, 13, 14, 18, 15, 18, 21, 23, 22, 19, 22, 16, 9, 16, 19, 15, 11, 7, 8, 6, 8, 9, 3, 4, 3, 2, 1, 0) # Alberithm


routeNodes <- routeNodes + 1 # since R is 1-indexed, we'll need this in a loop later
```

## Find route edges
```{r}
# Find route edges
nNodes <- length(routeNodes) # Number of nodes visited, including start/end
nEdges = nNodes - 1 # Number of edges on route is one less than number of nodes on route

routeEdges <- data.frame(start=c(0), end=c(0))

for (i in seq(nEdges)) {
  routeEdges[i,1] <- routeNodes[i]
  routeEdges[i,2] <- routeNodes[i+1]
}
routeEdges
```

## Find route coordinates
```{r}
# Find route coordinates
routeEdgeCoords <- data.frame(fromLat=c(0), fromLon=c(0), toLat=c(0), toLon=c(0))

for (i in seq(nEdges)) {
  j = routeNodes[i]
  k = routeNodes[i+1]
  routeEdgeCoords[i,1] <- intersectionCoords[j,1] # From latitude
  routeEdgeCoords[i,2] <- intersectionCoords[j,2] # From longitude
  routeEdgeCoords[i,3] <- intersectionCoords[k,1] # To latitude
  routeEdgeCoords[i,4] <- intersectionCoords[k,2] # To longitude
}
routeEdgeCoords
```

```{r}
# Test mode, only takes the first 3 edges
# routeEdgeCoords <- head(routeEdgeCoords, 3)
```

```{r}
# Initialization
library(googleway)
key = "INSERT-KEY-HERE" # Google Maps Directions API
map_key = "AIzaSyCl_U7ctGUodLktDtw-o4Q1tUA3g8c5e70"


routeEdgeCoordsDecoded <- c() # polylines
routeEdgeCoordsEncoded <- c() # polylines
N <- dim(routeEdgeCoords)[1] # number of loop iterations

for (i in seq(N)) {
  # Obtain route
  df <- google_directions(origin = c(routeEdgeCoords[i,1], routeEdgeCoords[i,2]),
                          destination = c(routeEdgeCoords[i,3], routeEdgeCoords[i,4]),
                          key = key,
                          mode = "walking",
                          simplify = TRUE)
  
  # Decode route:
  polyline <- df$routes$overview_polyline$points
  # routeEdgeCoordsDecoded will be a list of dataframes, but for some reason the individual list elements needs to be converted into dataframe before use
  routeEdgeCoordsDecoded <- c(routeEdgeCoordsDecoded, list(data.frame(decode_pl(polyline))))
  routeEdgeCoordsEncoded <- c(routeEdgeCoordsEncoded, list(data.frame(polyline)))
}

```

```{r}
routeEdgeCoordsDecodedMerged <- do.call("rbind", routeEdgeCoordsDecoded)
```


```{r}
# Plotting of route
google_map(key = map_key) %>%
add_polylines(data = routeEdgeCoordsDecodedMerged, lat="lat", lon="lon", stroke_weight = 6, stroke_colour='blue')

# google_map(key = map_key) %>%
# add_polylines(data = data.frame(routeEdgeCoordsEncoded[1]), polyline = "polyline", stroke_weight = 6, stroke_colour='blue')
```

{lat: 22.291, lng: 153.027}, {lat: 18.291, lng: 153.027}]

```{r}
# Export merged polyline to csv
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

write.csv(routeEdgeCoordsDecodedMerged, file = "route.csv", row.names = FALSE)
```

